# Generated by Django 4.2.5 on 2023-09-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
        ('equipo', '0002_user_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_asignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea.tarea')),
                ('user_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.user_equipo')),
            ],
            options={
                'db_table': 'tarea_asignada',
            },
        ),
    ]
